default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_language_version:
    python: python3.9

repos:
-   repo: https://github.com/korawica/clishelf
    rev: v0.2.19
    hooks:
    -   id: shelf-commit-msg
